import { AuthHeader } from "@/components/auth/header";
import { Button } from "@/components/ui/button";
import { LOGIN_URL } from "@/navigation/urls";
import { MoveLeftIcon } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import { ForgotPasswordForm } from "./forgot-password-form";

export const metadata: Metadata = {
  title: "Recupere sua senha",
  description: "Generated by create next app",
};

export default function ForgotPasswordPage() {
  return (
    <div className="mx-auto w-full max-w-[360px] items-center">
      <div className="flex w-full flex-col items-center justify-center space-y-8">
        <AuthHeader
          title="Esqueci minha senha"
          subtitle="Preencha seu e-mail utilizado para criar sua conta"
        />
        <ForgotPasswordForm />
        <div className="flex flex-col items-center">
          <Link href={LOGIN_URL} className="space-x-3">
            <Button
              variant="ghost"
              className="font-bold"
              startIcon={<MoveLeftIcon />}
            >
              Voltar para o login
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
