
version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: hubla-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./apps/hubla-backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - hubla-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: hubla-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - hubla-network

  # hubla-backend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/hubla-backend/Dockerfile
  #   container_name: hubla-backend
  #   command: yarn start:dev
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - ./apps/hubla-backend/.env
  #   volumes:
  #     - ./apps/hubla-backend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - postgres
  #   networks:
  #     - hubla-network

  # hubla-frontend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/hubla-frontend/Dockerfile
  #   container_name: hubla-frontend
  #   command: yarn dev
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./apps/hubla-frontend/.env
  #   volumes:
  #     - ./apps/hubla-frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - hubla-network

volumes:
  postgres:
    name: hubla-postgres

networks:
  hubla-network:
    driver: bridge
