version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: hubla-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./apps/hubla-backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - hubla-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: hubla-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@hub.la}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Abcd123!}
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - hubla-network

volumes:
  postgres:
    name: hubla-postgres

networks:
  hubla-network:
    driver: bridge
